name: Build WSODWarrior

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Clone and set up N-Gage SDK
      run: |
        echo "Cloning N-Gage SDK..."
        git clone https://github.com/ngagesdk/ngage-toolchain.git $HOME/ngage-toolchain
        export NGAGESDK=$HOME/ngage-toolchain
      env:
        NGAGESDK: $HOME/ngage-toolchain

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build

    - name: Configure CMake
      run: |
        mkdir -p build
        cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -G Ninja \
          -DNGAGESDK=${NGAGESDK}

    - name: Build the project
      run: |
        cd build
        cmake --build . --verbose

    - name: Verify built files
      run: |
        ls -al build/mmc/system/updates
