name: Build WSODWarrior

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        choco install cmake
        choco install ninja
        choco install git
        choco install mingw

    - name: Clone and set up N-Gage SDK
      run: |
        git clone https://github.com/ngagesdk/ngage-toolchain.git C:\ngage-toolchain
      env:
        NGAGESDK: C:\ngage-toolchain

    - name: Set environment variables for compilers
      run: |
        setx CC "C:\ngage-toolchain\gcc\bin\gcc.exe"
        setx CXX "C:\ngage-toolchain\gcc\bin\g++.exe"
      shell: cmd

    - name: Configure CMake
      env:
        NGAGESDK: C:\ngage-toolchain
        CC: C:\ngage-toolchain\gcc\bin\gcc.exe
        CXX: C:\ngage-toolchain\gcc\bin\g++.exe
      run: |
        mkdir build
        cd build
        cmake .. ^
          -DCMAKE_BUILD_TYPE=Release ^
          -DCMAKE_TOOLCHAIN_FILE=%NGAGESDK%\cmake\ngage-toolchain.cmake ^
          -DCMAKE_C_COMPILER=%CC% ^
          -DCMAKE_CXX_COMPILER=%CXX%

    - name: Build the project
      run: |
        cd build
        cmake --build . --verbose

    - name: Verify built files
      run: |
        dir build\mmc\system\updates
