name: Build WSODWarrior

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build gcc g++ git

    - name: Clone and set up N-Gage SDK
      run: |
        git clone https://github.com/ngagesdk/ngage-toolchain.git /home/runner/ngage-toolchain
      env:
        NGAGESDK: /home/runner/ngage-toolchain

    - name: Configure CMake
      env:
        NGAGESDK: /home/runner/ngage-toolchain
      run: |
        mkdir -p build
        cd build
        cmake .. \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_TOOLCHAIN_FILE=${NGAGESDK}/cmake/ngage-toolchain.cmake \
          -DCMAKE_C_COMPILER=/usr/bin/gcc \
          -DCMAKE_CXX_COMPILER=/usr/bin/g++

    - name: Build the project
      run: |
        cd build
        cmake --build . --verbose
      env:
        NGAGESDK: /home/runner/ngage-toolchain

    - name: Verify built files
      run: |
        ls -al build/mmc/system/updates
